### ISSUE TITLE
Unable to make it working

### ISSUE THREAD

**Issue by leoniDEV** [Quramy/typescript-eslint-language-service#18]
I'm unable to get errors in editors, I've try with different versions of Typescript, Eslint, @typescpt-eslint/parser (either older or newer versions).
It doesn't work also in Visual Studio.

I don't know how to diagnose this issue, I have no clue where to look at. In the tsserver.log seems that the plugin was load correctly but no error show up in the editor:
```
Info 27   [8:14:23.524] Enabling plugin typescript-eslint-language-service from candidate paths: c:/Users/leoniDAM/Dev/Projects/Pretty/tsplugin/node_modules/typescript/lib/tsserver.js/../../..
Info 28   [8:14:23.525] Loading typescript-eslint-language-service from c:/Users/leoniDAM/Dev/Projects/Pretty/tsplugin/node_modules/typescript/lib/tsserver.js/../../.. (resolved to c:/Users/leoniDAM/Dev/Projects/Pretty/tsplugin/node_modules/node_modules)
Info 29   [8:14:25.399] [typescript-eslint-language-service] config: [object Object]
Info 30   [8:14:25.407] Plugin validation succeded
[...]
Info 91   [8:14:28.515] [typescript-eslint-language-service] use '@typescript-eslint/parser'
```
this with:
 ```
typescript: 3.5.3
eslint: 6.0.1
@typescript-eslint/parser:  2.0.0
@typescript-eslint/eslint-plugin: 2.0.0
typescript-eslint-language-service: 1.4.0
```

Instead with the latest versions of the packages in the tsserver.log I have:
```
Info 27   [8:42:22.829] Enabling plugin typescript-eslint-language-service from candidate paths: c:/Users/leoniDAM/Dev/Projects/Pretty/tsplugin/node_modules/typescript/lib/tsserver.js/../../..
Info 28   [8:42:22.829] Loading typescript-eslint-language-service from c:/Users/leoniDAM/Dev/Projects/Pretty/tsplugin/node_modules/typescript/lib/tsserver.js/../../.. (resolved to c:/Users/leoniDAM/Dev/Projects/Pretty/tsplugin/node_modules/node_modules)
Info 29   [8:42:24.704] Failed to load module 'typescript-eslint-language-service' from c:/Users/leoniDAM/Dev/Projects/Pretty/tsplugin/node_modules/node_modules: Error: Cannot find module '@typescript-eslint/parser/dist/simple-traverse'
[...]
Info 30   [8:42:24.704] Couldn't find typescript-eslint-language-service
```
```
typescript: 3.7.2
eslint: 6.6.0
@typescript-eslint/eslint-plugin: 2.8.0
@typescript-eslint/parser: 2.8.0
typescript-eslint-language-service: 1.4.0
```

The .eslintrc.json is:
```json
{
  "root": true,
  "env": {
    "browser": true,
    "es6": true
  },
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": 2018,
    "sourceType": "module",
    "project": "./tsconfig.json"
  },
  "plugins": [
    "@typescript-eslint"
  ],
  "rules": {
    "no-var": "error"
  }
}
```

and the tsconfig.json:
```json
{
  "compilerOptions": {
    "target": "es2017" ,
    "module": "es6",

    "strict": true,

    "noUnusedLocals": true, 
    "noUnusedParameters": true, 
    "noImplicitReturns": true, 
    "noFallthroughCasesInSwitch": true,

    "plugins": [
      {
        "name": "typescript-eslint-language-service"
      }
    ]
  }
}
```

The version of VSCode is `1.41.0-insider` the version of Visual Studio is `16.4.0 Preview 5.0`

**Comment by AObuchow** [comment]
I was also facing the same issue. It seems that `@typescript-eslint/parser/dist/simple-traverse.js` was removed from `typescript-eslint` at some point. I worked around this issue by using an older version (2.0.0) of the typescript-eslint parser and plugin. Unforunately, it seems you've already tried that with no success.

In my case, after downgrading I'm now getting issues related to the AST converter in @typescript-eslint (maybe a versioning issue). So I'm unable to get it working and still trying to figure out a fix.

Let me know if you make any progress.

**Comment by leoniDEV** [comment]
At the moment I switched back to TSLint

**Comment by Quramy** [comment]
Thanks for your reporting.
I’ll check this 🙇

**Comment by Quramy** [comment]
Hi. It's `typescript-eslint` version problem.
I've fixed and released my plugin for @typescript-eslint/parser >= 2.8. Please check https://www.npmjs.com/package/typescript-eslint-language-service/v/2.0.0 out.

**Comment by leoniDEV** [comment]
Still doesn't works, now in tsserver.log I got:
```
Info 29   [14:44:47.546] Failed to load module 'typescript-eslint-language-service' from c:/Users/leoniDAM/Dev/Projects/Pretty/tsplugin/node_modules/node_modules: Error: Cannot find module 'eslint/lib/cli-engine/ignored-paths'
```

**Comment by hellocontrol-bng** [comment]
Please reopen this. @leoniDEV is right, it doesn't work still for me either.

I recommend moving away from `ignored-paths` as that has been removed from eslint. Have you considered using `eslint/lib/cli-engine/file-enumerator`? There is a method `FileEnumerator._isIgnoredFile()` there.
