### ISSUE TITLE
What's the advantage of this tool compared to normal vscode-eslint and CLI tooling?

### ISSUE THREAD

**Issue by FunctionDJ** [Quramy/typescript-eslint-language-service#290]
This tool/plugin got me interested, but with an existing TypeScript + ESLint setup i'm confused on what it adds.

If i understand correctly, this tool helps in places where there's no ESLint IDE plugin, but TypeScript language server error feedback.

In my projects i usually have TypeScript and ESLint set up normally with the vscode-eslint plugin to see ESLint errors in VSCode, and i use the ESLint CLI and `tsc --noEmit` in my tooling for automated code checks. Am i still missing out on something?

**Comment by Quramy** [comment]
> Am i still missing out on something?

If all your project members use only VSC, you don't need to install my plugin. 

My plugin is a TypeScript language service plugin and is agnostic for IDE/Editors, e.g. emacs, Vim. 

The following is my presentation about why I've developed this plugin. Please check it out if you're intereseted.
https://quramy.github.io/ts-eslint-talk/#slide=18

**Comment by FunctionDJ** [comment]
Thank you very much for your response! :)

**Comment by wSedlacek** [comment]
@Quramy You mentioned performance in your slides, are there any benchmarks on how much faster this is?
