### ISSUE TITLE
Don't get errors with typescript-eslint 3.0.0

### ISSUE THREAD

**Issue by leoniDEV** [Quramy/typescript-eslint-language-service#33]
I don't get errors with `typescript-eslint 3.0.0`.

the TSServer.log report:
`Info 73   [21:19:5.370] [typescript-eslint-language-service] Cannot read property '0' of undefined`

running ESLint from command line reports the right errors.
In the package.json I have:
```JSON
"devDependencies": {
    "typescript": "^3.9.0",
    "eslint": "^7.1.0",
    "@typescript-eslint/parser": "^3.0.0",
    "@typescript-eslint/typescript-estree": "^3.0.0",
    "@typescript-eslint/eslint-plugin": "^3.0.0",
    "typescript-eslint-language-service": "^2.1.8"
  }
```

it works with `typescript-eslint 2.8.0`.

**Comment by Quramy** [comment]
I published typescript-eslint-language-service@3.0.0, which is compatible for ESLint >= 7.x.x and `@typescript-eslint` tools >= 3.0.0. Pls check out this!
