### ISSUE TITLE
Visitor Keys was moved into an extra package

### ISSUE THREAD

**Issue by enko** [Quramy/typescript-eslint-language-service#42]
https://github.com/Quramy/typescript-eslint-language-service/blob/c914a7bb16cc912caea7387ad4bdbd470d053b86/src/ast-converter.ts#L6

https://www.npmjs.com/package/@typescript-eslint/visitor-keys

I tried to replace it in my node_modules and it seems to work:

```
const visitor_keys_1 = require("@typescript-eslint/visitor-keys");
```

I don't know if there are any other unrelated issues with that.

**Comment by mc-petry** [comment]
Same for me.
Not works with `typescript-eslint/eslint-plugin` v**3.9.0**

**Comment by Quramy** [comment]
Thx for reporting!
