### ISSUE TITLE
Can't load eslint configs after eslint@8.35.0

### ISSUE THREAD

**Issue by andyrooger** [Quramy/typescript-eslint-language-service#523]
When using eslint configs e.g.

```js
extends: [
        'eslint:recommended',
]
```

The configs cannot be found when using eslint@8.35.0 or later. [This PR](https://github.com/eslint/eslint/pull/16844) moved their location so that `resolveESLintIntrinsicConfigPath` can no longer resolve them.

**Comment by Quramy** [comment]
Thanks to point PRs .

**Comment by andyrooger** [comment]
Thanks! Very quick work! @Quramy

**Comment by Quramy** [comment]
Your info helps me so much because I did not know why renovate PR is failed.

Thanks.
