### ISSUE TITLE
Multiple errors running in Windows

### ISSUE THREAD

**Issue by andyrooger** [Quramy/typescript-eslint-language-service#525]
I've been having trouble running this plugin since around v5.0.0 on my Windows machine. Tracked the problem down to a couple of file path checks - all to do with paths having back or forwards slashes in them:

- [checkFileToBeIgnored](https://github.com/Quramy/typescript-eslint-language-service/blob/master/src/eslint-adapter.ts#L147) - in Windows the path contains `node_modules\\` rather than `node_modules/`
- [isParserModuleNameValid](https://github.com/Quramy/typescript-eslint-language-service/blob/master/src/eslint-adapter.ts#L219) - in Windows we get `@typescript-eslint\\parser` in the full path (present in the final config) rather than `@typescript-eslint/parser`
- [resolveESLintIntrinsicConfigPath](https://github.com/Quramy/typescript-eslint-language-service/blob/master/src/eslint-config-provider.ts#L73) - I think the assembled path with `/` in is fine, but the split fails to find the forward slash in the resolved paths.

Happy to submit a PR to make this more OS-agnostic if you would like?

**Comment by Quramy** [comment]
> Happy to submit a PR to make this more OS-agnostic if you would like?

👍

**Comment by awydler** [comment]
check possible duplicate #466 
There is also an open PR: #467
