### ISSUE TITLE
Peer dependencies syntax incorrect?

### ISSUE THREAD

**Issue by mglimmerveen** [Quramy/typescript-eslint-language-service#9]
Hi, 
I've tried installing your plugin. However, I get the message that I don't have the correct peer dependency installed, while I believe I do:

Now I saw you defined the peer dependencies as:
`"eslint": "^4.0.0 | ^5.0.0 | ^6.0.0",`

Now, I'm still a bit to the npm dependencies, but I think the correct syntax should be:
`"eslint": "^4.0.0 || ^5.0.0 || ^6.0.0",`

**Comment by Quramy** [comment]
@mglimmerveen 
Thanks your pointing and I fixed via 8e10660ff6d99885aed829c4b211c605e4a4d36a 🙇
